name: rps
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - scipy
  - matplotlib
  - tqdm
  - pillow
  - sounddevice
  - attrs
  - cffi
  - typing_extensions
  - opencv
  - pytorch-cpu
  - torchvision
  - torchaudio

  - pip:
      - -r requirements.txt
