name: rps
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip

  - pip:
      - absl-py==2.3.1
      - attrs==25.4.0
      - cffi==2.0.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - imutils==0.5.4
      - jax==0.6.2
      - jaxlib==0.6.2
      - Jinja2==3.1.6
      - kiwisolver==1.4.9
      - MarkupSafe==2.1.5
      - matplotlib==3.10.7
      - mediapipe==0.10.14
      - ml_dtypes==0.5.4
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - opencv-contrib-python==4.12.0.88
      - opencv-python==4.12.0.88
      - opt_einsum==3.4.0
      - packaging==25.0
      - pillow==11.3.0
      - protobuf==4.25.8
      - pycparser==2.23
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - scipy==1.15.3
      - six==1.17.0
      - sounddevice==0.5.3
      - sympy==1.14.0
      - torch==2.9.1+cpu
      - torchaudio==2.9.1+cpu
      - torchvision==0.24.1+cpu
      - tqdm==4.67.1
      - typing_extensions==4.15.0
